language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose up -d

script:
  - docker-compose exec web python manage.py test

after_script:
  - docker-compose down

deploy:
  run: python3 manage.py migrate
  provider: heroku
  api_key: 
    secure: 5f03ab22-2e3d-4267-b738-54c420172c16
  app: ancient-inlet-56922
  on:
    repo: gr8temi/agrispace-API