language: python
python:
  - "3.6"

services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - pip install docker-compose
  - docker-compose up -d

script:
  - docker-compose exec web python manage.py test

after_script:
  - docker-compose down

deploy:
  run: python3 manage.py migrate
  provider: heroku
  api_key: 
    secure: 5f03ab22-2e3d-4267-b738-54c420172c16
  app: ancient-inlet-56922
  on:
    repo: gr8temi/agrispace-API