version: '3'
services:
  web:
    build: .
    environment:
      - DEBUG=$DEBUG
      - CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/api"
    ports:
      - "8000:8000"
